research_task:
  description: >
    Conduct in-depth research on {topic}, ensuring the findings are up-to-date for the year {current_year}.  
    Identify key insights, trends, and relevant information.  
  expected_output: >
    A list of news articles about{topic} with title,url and snippet  
  agent: researcher  

reporting_task:
  description: >
    Analyze the research findings and expand each key point into a comprehensive section.  
    Provide detailed explanations, context, and any supporting data.  
  expected_output: >
    A well-structured report in markdown format, with each key topic expanded into a full section.  
  agent: reporting_analyst  
